name: cTensor Tests

on:
  push:
    branches: [ main, test, develop ]
  pull_request:
    branches: [ main, test, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        compiler: [gcc, clang]
        build_type: [Debug, Release]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential python3 python3-pip
        pip3 install torch numpy
    
    - name: Generate reference data
      run: |
        cd tests
        python3 generate_reference_data.py
    
    - name: Configure CMake (Debug)
      if: matrix.build_type == 'Debug'
      run: |
        cd tests
        cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=${{ matrix.compiler }}
    
    - name: Configure CMake (Release)
      if: matrix.build_type == 'Release'
      run: |
        cd tests
        cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=${{ matrix.compiler }}
    
    - name: Build tests
      run: |
        cd tests
        cmake --build build --config ${{ matrix.build_type }}
    
    - name: Run tests
      run: |
        cd tests
        ctest --test-dir build --output-on-failure --verbose
    
    - name: Run tests directly (for detailed output)
      run: |
        cd tests/build
        ./cten_tests

  test-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Python dependencies
      run: |
        pip install torch numpy
    
    - name: Generate reference data
      run: |
        cd tests
        python generate_reference_data.py
    
    - name: Configure CMake
      run: |
        cd tests
        cmake -B build -DCMAKE_BUILD_TYPE=Release
    
    - name: Build tests
      run: |
        cd tests
        cmake --build build --config Release
    
    - name: Run tests
      run: |
        cd tests
        ctest --test-dir build --output-on-failure --verbose
    
    - name: Run tests directly (for detailed output)
      run: |
        cd tests/build/Release
        ./cten_tests.exe

  test-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Python dependencies
      run: |
        pip install torch numpy
    
    - name: Generate reference data
      run: |
        cd tests
        python3 generate_reference_data.py
    
    - name: Configure CMake
      run: |
        cd tests
        cmake -B build -DCMAKE_BUILD_TYPE=Release
    
    - name: Build tests
      run: |
        cd tests
        cmake --build build --config Release
    
    - name: Run tests
      run: |
        cd tests
        ctest --test-dir build --output-on-failure --verbose
    
    - name: Run tests directly (for detailed output)
      run: |
        cd tests/build
        ./cten_tests